use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/XXCommonTools/XXRepos.git'


target 'MBHudManager_Example' do
    
  pod 'MBHudManager', :path => '../'

  target 'MBHudManager_Tests' do
    inherit! :search_paths


  end
end
